### ISSUE TITLE
Output only tag "Version" but no further

### ISSUE THREAD

**Issue by n-ice-ch** [sanket143/id3#1]
The example code gives on my example mp3 file only the tag "Version: V2.2.0".
![mp3_id3](https://user-images.githubusercontent.com/51759985/72648782-366c0c00-397c-11ea-834a-8a93fd8b60e9.png)

It looks like there are no more tags.

But the tool "MP3tag v2.99a" from here: https://www.mp3tag.de/
gives all tags without issues:
![mp3_tags](https://user-images.githubusercontent.com/51759985/72648676-f60c8e00-397b-11ea-9313-ae1856e4ec4a.png)

What is going wrong with my dart code?

**Comment by sanket143** [comment]
this should resolve this issue https://github.com/sanket143/id3/pull/6
