### ISSUE TITLE
Cuts off part of the text of the tag AdditionalInfo

### ISSUE THREAD

**Issue by technoqz** [sanket143/id3#5]
if the AdditionalInfo tag(comment) contains very long text, it will print only part of it. 
[track_sample.zip](https://github.com/sanket143/id3/files/4967075/track_sample.zip)

**Comment by 1-alok** [comment]
See this

https://stackoverflow.com/questions/61439549/how-to-use-id3-plugging-in-flutter

**Comment by sanket143** [comment]
resolved in https://github.com/sanket143/id3/pull/6
